export const LADAS_MEXICO = [
  { state: 'Ciudad de México', lada: ['55'] },
  { state: 'Puebla, Puebla', lada: ['220', '221', '222']},
  { state: 'Guadalajara, Jalisco', lada: ['33'] },
  { state: 'Monterrey, Nuevo León', lada: ['81'] },
  { state: 'Chihuahua, Chihuahua', lada: ['614'] },
  { state: 'Mérida, Yucatán', lada: ['999', '990'] },
  { state:'Saltillo, Coahuila', lada: ['844'] },
  { state: 'Aguascalientes, Aguascalientes', lada: ['449'] },
  { state: 'Hermosillo, Sonora', lada: ['662'] },
  { state: 'Mexicali, Baja California', lada: ['686'] },
  { state: 'San Luis Potosí, San Luis Potosí', lada: ['444', '440'] },
  { state: 'Culiacán, Sinaloa', lada: ['667'] },
  { state: 'Queretaro, Querétaro', lada: ['442', '446'] },
  { state: 'Morelia, Michoacán', lada: ['443'] },
  { state: 'Durango, Durango', lada: ['618'] },
  { state: 'Tuxtla Gutiérrez, Chiapas', lada: ['961'] },
  { state: 'Xalapa, Veracruz', lada: ['228'] },
  { state: 'Tepic, Nayarit', lada: ['311'] },
  { state: 'Cuernavaca, Morelos', lada: ['777'] },
  { state: 'Villahermosa, Tabasco', lada: ['993'] },
  { state: 'Ciudad Victoria, Tamaulipas', lada: ['834'] },
  { state: 'Pachuca, Hidalgo', lada: ['771'] },
  { state: 'Oaxaca, Oaxaca', lada: ['951'] },
  { state: 'La paz, Baja California Sur', lada: ['612'] },
  { state: 'Campeche, Campeche', lada: ['981'] },
  { state: 'Chilpancingo, Guerrero', lada: ['747'] },
  { state: 'Toluca, Estado de México', lada: ['722', '720', '729'] },
  { state: 'Chetumal, Quintana Roo', lada: ['983'] },
  { state: 'Colima, Colima', lada: ['312'] },
  { state: 'Zacatecas, Zacatecas', lada: ['492'] },
  { state: 'Guanajuato, Guanajuato', lada: ['473'] },
  { state: 'Tlaxcala, Tlaxcala', lada: ['246'] },
]